# Permalinks
permalink:           /blog/:year/:month/:day/:title/

# Setup
title:               ls-al.me
tagline:             hello, world!
description:         ''
url:                 http://ls-al.me
baseurl:             ''
paginate:            5
paginate_path:       blog/page:num/
markdown:            kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# About/contact
author:
  name:              Hyeonseop Lee
  email:             hyeonseop@ls-al.me
  github:            protos37
  gravatar:          765306136df4172beccebe0859a84ad1
