# Permalinks
permalink:           pretty

# Setup
title:               protos
tagline:             blog
description:         ''
url:                 https://protos37.github.io
baseurl:             ''
paginate:            5
markdown:            redcarpet
redcarpet:
  extensions:        ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables", "with_toc_data"]

# About/contact
author:
  name:              Hyeonseop Lee
  email:             hyeonseop@ls-al.me
