# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               protos
tagline:             blog
description:         ''
url:                 https://protos37.github.io
baseurl:             ''
paginate:            5
markdown:            redcarpet
redcarpet:
  extensions:        ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables", "with_toc_data"]

# About/contact
author:
  name:              Lee Hyeonseop
  email:             protos37@gmail.com
